"""Google connector internals grouped by lifecycle, transport, and read policy."""

from .credentials import (
    FileGoogleCredentialStore,
    GoogleConnectionBinding,
    GoogleConnectionSnapshot,
    GoogleCredentialStore,
    InMemoryGoogleCredentialStore,
)
from .http import (
    GOOGLE_HTTP_TIMEOUT_SECONDS,
    MAX_GOOGLE_HTTP_RESPONSE_BYTES,
    GoogleHttpError,
    GoogleHttpMethod,
    GoogleHttpResponse,
    GoogleHttpTransport,
    UrllibGoogleHttpTransport,
    ensure_bounded_response_body,
    read_bounded_response_body,
)
from .oauth_connector import GoogleOAuthConnector
from .oauth_lifecycle import GoogleOAuthLifecycle
from .oauth_models import (
    GOOGLE_OAUTH_BASELINE_SCOPES,
    GOOGLE_OAUTH_SCOPES,
    GOOGLE_OAUTH_STATE_TTL,
    GOOGLE_OAUTH_TRACE_PAYLOAD_LIMIT_BYTES,
    GoogleConnectionState,
    GoogleOAuthError,
    OAuthAuthorization,
    OAuthCallbackResponse,
    OAuthCredentialRecord,
    OAuthExchangeError,
    OAuthGrant,
)
from .oauth_provider import (
    ControlledGoogleOAuthProvider,
    GoogleLiveOAuthProvider,
    GoogleOAuthProvider,
)
from .oauth_state import (
    GoogleOAuthStateStore,
    InMemoryGoogleOAuthStateStore,
    SQLiteGoogleOAuthStateStore,
)
from .read_connector import GoogleReadConnector, build_live_google_read_connector
from .read_models import (
    DEFAULT_MAX_ITEM_BYTES,
    DEFAULT_MAX_RESULT_BYTES,
    DEFAULT_MAX_RESULT_ITEMS,
    DRIVE_READ_SCOPE,
    GMAIL_READ_SCOPE,
    GOOGLE_READ_SCOPES,
    GOOGLE_READ_TRACE_PAYLOAD_LIMIT_BYTES,
    MAX_ITEM_BYTES,
    MAX_RESULT_BYTES,
    MAX_RESULT_ITEMS,
    GoogleReadError,
    GoogleReadOperation,
    GoogleReadProviderError,
    GoogleReadProviderResult,
    GoogleReadRequest,
    GoogleReadResult,
    GoogleReadTracePayload,
)
from .read_provider import (
    MAX_PROVIDER_RESPONSE_BYTES,
    ControlledGoogleReadProvider,
    GoogleApiReadProvider,
    GoogleReadProvider,
)
from .read_tools import (
    DriveReadInput,
    GmailReadInput,
    GoogleReadOutput,
)
from .token_auth import (
    GOOGLE_TOKEN_URL,
    GoogleRefreshTokenExchanger,
    GoogleTokenExchangeError,
    GoogleTokenExchangeRequest,
    GoogleTokenExchangeResult,
)

GoogleReadHttpResponse = GoogleHttpResponse
GoogleReadHttpTransport = GoogleHttpTransport
UrllibGoogleReadHttpTransport = UrllibGoogleHttpTransport

__all__ = [
    "DEFAULT_MAX_ITEM_BYTES",
    "DEFAULT_MAX_RESULT_BYTES",
    "DEFAULT_MAX_RESULT_ITEMS",
    "DRIVE_READ_SCOPE",
    "GMAIL_READ_SCOPE",
    "GOOGLE_HTTP_TIMEOUT_SECONDS",
    "GOOGLE_OAUTH_BASELINE_SCOPES",
    "GOOGLE_OAUTH_SCOPES",
    "GOOGLE_OAUTH_STATE_TTL",
    "GOOGLE_OAUTH_TRACE_PAYLOAD_LIMIT_BYTES",
    "GOOGLE_READ_SCOPES",
    "GOOGLE_READ_TRACE_PAYLOAD_LIMIT_BYTES",
    "GOOGLE_TOKEN_URL",
    "MAX_GOOGLE_HTTP_RESPONSE_BYTES",
    "MAX_ITEM_BYTES",
    "MAX_PROVIDER_RESPONSE_BYTES",
    "MAX_RESULT_BYTES",
    "MAX_RESULT_ITEMS",
    "ControlledGoogleOAuthProvider",
    "ControlledGoogleReadProvider",
    "DriveReadInput",
    "FileGoogleCredentialStore",
    "GmailReadInput",
    "GoogleApiReadProvider",
    "GoogleConnectionBinding",
    "GoogleConnectionSnapshot",
    "GoogleConnectionState",
    "GoogleCredentialStore",
    "GoogleHttpError",
    "GoogleHttpMethod",
    "GoogleHttpResponse",
    "GoogleHttpTransport",
    "GoogleLiveOAuthProvider",
    "GoogleOAuthConnector",
    "GoogleOAuthError",
    "GoogleOAuthLifecycle",
    "GoogleOAuthProvider",
    "GoogleOAuthStateStore",
    "GoogleReadConnector",
    "GoogleReadError",
    "GoogleReadHttpResponse",
    "GoogleReadHttpTransport",
    "GoogleReadOperation",
    "GoogleReadOutput",
    "GoogleReadProvider",
    "GoogleReadProviderError",
    "GoogleReadProviderResult",
    "GoogleReadRequest",
    "GoogleReadResult",
    "GoogleReadTracePayload",
    "GoogleRefreshTokenExchanger",
    "GoogleTokenExchangeError",
    "GoogleTokenExchangeRequest",
    "GoogleTokenExchangeResult",
    "InMemoryGoogleCredentialStore",
    "InMemoryGoogleOAuthStateStore",
    "OAuthAuthorization",
    "OAuthCallbackResponse",
    "OAuthCredentialRecord",
    "OAuthExchangeError",
    "OAuthGrant",
    "SQLiteGoogleOAuthStateStore",
    "UrllibGoogleHttpTransport",
    "UrllibGoogleReadHttpTransport",
    "build_live_google_read_connector",
    "ensure_bounded_response_body",
    "read_bounded_response_body",
]
